using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.Migrations
{
    /// <summary>
    /// ?? ASSIGNMENT 2.4 & 3.1 - Initial Identity Migration
    /// 
    /// ?? WHAT IS A MIGRATION?
    /// A migration is like a "recipe card" for your database:
    /// - Up() = How to BAKE the cake (create tables)
    /// - Down() = How to UNBAKE the cake (remove tables)
    /// 
    /// ?? WHY MIGRATIONS?
    /// - Version control for your database schema
    /// - Can roll back changes if something goes wrong
    /// - Consistent across all environments (dev, test, prod)
    /// - Generated by EF Core, not written by hand!
    /// 
    /// ?? THIS MIGRATION:
    /// Created by: dotnet ef migrations add InitialIdentity
    /// Purpose: Creates all ASP.NET Identity tables for authentication
    /// </summary>
    /// <inheritdoc />
    public partial class InitialIdentity : Migration
    {
        /// <summary>
        /// ?? UP METHOD - APPLY MIGRATION
        /// 
        /// ?? WHAT HAPPENS:
        /// When you run: dotnet ef database update
        /// This method runs and CREATES all the Identity tables
        /// 
        /// ?? SQLITE NOTES:
        /// - "TEXT" is SQLite's string type
        /// - "INTEGER" is SQLite's boolean/number type
        /// - SQLite doesn't have real foreign key constraints by default
        ///   but EF simulates them with this syntax
        /// </summary>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ====================================================================
            // ?? TABLE 1: AspNetRoles
            // ====================================================================
            
            /// <summary>
            /// ?? ROLES TABLE
            /// Stores all available roles in the system.
            /// 
            /// Examples: "Admin", "Employee", "Receptionist", "Facilities Manager"
            /// 
            /// Columns:
            /// - Id: Unique identifier for the role
            /// - Name: Display name (e.g., "Admin")
            /// - NormalizedName: Uppercase version for fast lookups (e.g., "ADMIN")
            /// - ConcurrencyStamp: For handling concurrent updates
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            // ====================================================================
            // ?? TABLE 2: AspNetUsers
            // ====================================================================
            
            /// <summary>
            /// ?? USERS TABLE
            /// Stores all user accounts in the system.
            /// 
            /// This extends IdentityUser - all these columns come for FREE!
            /// 
            /// Key columns:
            /// - Id: Unique user identifier (GUID string)
            /// - UserName: Login name (e.g., "Skye")
            /// - Email: User's email address
            /// - PasswordHash: NEVER plain text! Hashed password
            /// - EmailConfirmed: Has user verified email?
            /// - PhoneNumber: Contact number
            /// - LockoutEnd: When lockout expires (null if not locked)
            /// - AccessFailedCount: Failed login attempts
            /// 
            /// ?? SECURITY:
            /// - Passwords are NEVER stored in plain text
            /// - Lockout prevents brute force attacks
            /// - TwoFactorEnabled for extra security
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    UserName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    PasswordHash = table.Column<string>(type: "TEXT", nullable: true),
                    SecurityStamp = table.Column<string>(type: "TEXT", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", nullable: true),
                    PhoneNumber = table.Column<string>(type: "TEXT", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "TEXT", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            // ====================================================================
            // ?? TABLE 3: AspNetRoleClaims
            // ====================================================================
            
            /// <summary>
            /// ?? ROLE CLAIMS TABLE
            /// Stores claims/permissions assigned to roles.
            /// 
            /// Example: Role "Admin" might have claim "CanDeleteRooms"
            /// 
            /// Columns:
            /// - Id: Unique claim ID
            /// - RoleId: Foreign key to AspNetRoles
            /// - ClaimType: Type of claim (e.g., "Permission")
            /// - ClaimValue: Value (e.g., "CanDeleteRooms")
            /// 
            /// ?? RELATIONSHIP:
            /// Many claims can belong to one role
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    RoleId = table.Column<string>(type: "TEXT", nullable: false),
                    ClaimType = table.Column<string>(type: "TEXT", nullable: true),
                    ClaimValue = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    // ?? CASCADE: If role is deleted, its claims are also deleted
                });

            // ====================================================================
            // ?? TABLE 4: AspNetUserClaims
            // ====================================================================
            
            /// <summary>
            /// ?? USER CLAIMS TABLE
            /// Stores claims/permissions assigned directly to users.
            /// 
            /// Example: User "Skye" might have claim "Department: IT"
            /// 
            /// Columns:
            /// - Id: Unique claim ID
            /// - UserId: Foreign key to AspNetUsers
            /// - ClaimType: Type of claim (e.g., "Department")
            /// - ClaimValue: Value (e.g., "IT")
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    ClaimType = table.Column<string>(type: "TEXT", nullable: true),
                    ClaimValue = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // ====================================================================
            // ?? TABLE 5: AspNetUserLogins
            // ====================================================================
            
            /// <summary>
            /// ?? USER LOGINS TABLE
            /// Stores external login providers (Google, Facebook, etc.)
            /// 
            /// Example: User logs in with Google
            /// 
            /// Columns:
            /// - LoginProvider: "Google", "Facebook", etc.
            /// - ProviderKey: User's ID from that provider
            /// - UserId: Foreign key to AspNetUsers
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetUserLogins",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(type: "TEXT", nullable: false),
                    ProviderKey = table.Column<string>(type: "TEXT", nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "TEXT", nullable: true),
                    UserId = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserLogins", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // ====================================================================
            // ?? TABLE 6: AspNetUserRoles
            // ====================================================================
            
            /// <summary>
            /// ?? USER ROLES TABLE (JUNCTION TABLE)
            /// Links users to roles (many-to-many relationship)
            /// 
            /// Example: 
            /// UserId "123" + RoleId "456" = User is in Admin role
            /// 
            /// Columns:
            /// - UserId: Foreign key to AspNetUsers
            /// - RoleId: Foreign key to AspNetRoles
            /// 
            /// ?? WHY JUNCTION TABLE?
            /// One user can have many roles
            /// One role can have many users
            /// This table connects them!
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetUserRoles",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    RoleId = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // ====================================================================
            // ?? TABLE 7: AspNetUserTokens
            // ====================================================================
            
            /// <summary>
            /// ?? USER TOKENS TABLE
            /// Stores authentication tokens (like password reset tokens)
            /// 
            /// Columns:
            /// - UserId: Foreign key to AspNetUsers
            /// - LoginProvider: Which provider issued token
            /// - Name: Token name
            /// - Value: Token value
            /// </summary>
            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    LoginProvider = table.Column<string>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Value = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // ====================================================================
            // ?? INDEXES (for performance)
            // ====================================================================
            
            /// <summary>
            /// ?? WHY INDEXES?
            /// Indexes make queries FASTER by organizing data like a book index.
            /// 
            /// These indexes are on foreign keys and lookup fields:
            /// - RoleId in RoleClaims (find all claims for a role)
            /// - NormalizedName in Roles (find role by name quickly)
            /// - UserId in UserClaims (find all claims for a user)
            /// - Email in Users (find user by email)
            /// - UserName in Users (find user by username)
            /// </summary>
            
            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                table: "AspNetRoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true);  // Role names must be unique!

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                table: "AspNetUserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserRoles_RoleId",
                table: "AspNetUserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true);  // Usernames must be unique!
        }

        /// <summary>
        /// ?? DOWN METHOD - ROLLBACK MIGRATION
        /// 
        /// ?? WHAT HAPPENS:
        /// When you run: dotnet ef migrations remove
        /// Or: dotnet ef database update PreviousMigration
        /// 
        /// This method runs and DROPS all the tables
        /// 
        /// ?? WHY HAVE DOWN?
        /// - Can roll back to previous state if something goes wrong
        /// - Enables development/testing with different schemas
        /// - Professional database management
        /// </summary>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // ?? Order matters! Drop child tables first (with foreign keys)
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            // ?? Then drop parent tables
            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "AspNetUsers");
        }
    }
}

/// <summary>
/// ?? EDUCATIONAL SUMMARY - IDENTITY TABLES RELATIONSHIP:
/// 
/// AspNetUsers (1) ------+
///      ¦                ¦
///      ¦                ?
///      ¦         AspNetUserRoles (Many-to-Many)
///      ¦                ¦
///      ?                ?
/// AspNetUserClaims (Many)  AspNetRoles (1)
///      ¦                        ¦
///      ¦                        ?
///      +-------------+    AspNetRoleClaims (Many)
///                    ¦
///              AspNetUserLogins (Many)
///                    ¦
///              AspNetUserTokens (Many)
/// 
/// ?? ASSIGNMENT REQUIREMENTS MET:
/// ? 2.4: Identity tables created
/// ? 3.1: Database schema for persistence
/// ? All relationships properly configured
/// 
/// ?? COMMANDS:
/// Create:  dotnet ef migrations add MigrationName
/// Apply:   dotnet ef database update
/// Remove:  dotnet ef migrations remove
/// Script:  dotnet ef migrations script
/// </summary>