using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    /// <summary>
    /// ?? ASSIGNMENT 3.1 & 3.2 - Database Model Snapshot
    /// 
    /// ?? WHAT IS A MODEL SNAPSHOT?
    /// Think of this as a PHOTOGRAPH of your database schema at a point in time.
    /// EF Core uses this file to remember what your database looks like.
    /// 
    /// ?? WHY IS THIS NEEDED?
    /// When you add a new migration, EF Core:
    /// 1. Looks at this snapshot (what the database looks like NOW)
    /// 2. Looks at your C# classes (what you WANT it to look like)
    /// 3. Compares them to generate the migration (what needs to CHANGE)
    /// 
    /// ?? KEY RULE: NEVER EDIT THIS FILE MANUALLY!
    /// This file is AUTOMATICALLY generated and updated by EF Core.
    /// If you need to change your database, change your entity classes
    /// and add a new migration - DON'T edit this file directly!
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207085944_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <summary>
        /// ?? BUILD TARGET MODEL
        /// 
        /// ?? WHAT THIS METHOD DOES:
        /// This method describes your ENTIRE database schema:
        /// - All tables
        /// - All columns with their types
        /// - Primary keys
        /// - Foreign keys
        /// - Indexes
        /// - Relationships
        /// 
        /// ?? WHEN IT'S USED:
        /// - When adding a new migration (to compare with current code)
        /// - When updating the database (to know what to create)
        /// - When scaffolding DbContext (to reverse engineer)
        /// 
        /// ?? WARNING: This is machine-generated code!
        /// It's meant to be READ by developers but NEVER EDITED directly.
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // ?? ProductVersion tells us which EF Core version created this
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // ====================================================================
            // ?? TABLE 1: AspNetUsers (ApplicationUser entity)
            // ====================================================================
            
            /// <summary>
            /// ?? USERS TABLE CONFIGURATION
            /// 
            /// This maps the ApplicationUser class to the AspNetUsers table.
            /// Each property becomes a column in the database.
            /// 
            /// ?? ASSIGNMENT 2.4 - Identity Integration:
            /// This is the core user table that stores all account information.
            /// 
            /// ?? Primary Key: Id (string/GUID)
            /// ?? Data Types: TEXT for strings, INTEGER for numbers/bools
            /// </summary>
            modelBuilder.Entity("ApplicationUser", b =>
                {
                    // ?? User ID - Primary Key
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // ?? Security properties
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");  // Failed login attempts
                    
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()  // For optimistic concurrency
                        .HasColumnType("TEXT");

                    // ?? Email properties
                    b.Property<string>("Email")
                        .HasMaxLength(256)  // Max length constraint
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");  // Has email been verified?

                    // ?? Lockout settings (brute force protection)
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");
                    
                    b.Property<DateTimeOffset?>("LockoutEnd")  // Nullable = not locked
                        .HasColumnType("TEXT");

                    // ?? Normalized fields for case-insensitive searching
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");
                    
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // ?? Password (hash, never plain text!)
                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    // ?? Phone number properties
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");
                    
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    // ?? Security stamp - changes when password changes
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    // ?? Two-factor authentication
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    // ?? Username
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // ?? Set primary key
                    b.HasKey("Id");

                    // ?? Indexes for fast lookups
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");  // Fast email search
                    
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()  // Usernames must be unique!
                        .HasDatabaseName("UserNameIndex");

                    // ?? Table name in database
                    b.ToTable("AspNetUsers", (string)null);
                });

            // ====================================================================
            // ?? TABLE 2: AspNetRoles (IdentityRole entity)
            // ====================================================================
            
            /// <summary>
            /// ?? ROLES TABLE
            /// Stores all available roles (Admin, Employee, etc.)
            /// 
            /// ?? Primary Key: Id
            /// ?? Index: NormalizedName (unique) for fast role lookup
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            // ====================================================================
            // ?? TABLE 3: AspNetRoleClaims
            // ====================================================================
            
            /// <summary>
            /// ?? ROLE CLAIMS TABLE
            /// Stores permissions/claims assigned to roles
            /// 
            /// ?? Primary Key: Id
            /// ?? Foreign Key: RoleId ? AspNetRoles.Id
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()  // Auto-increment
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");  // Index for faster lookups

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // ====================================================================
            // ?? TABLE 4: AspNetUserClaims
            // ====================================================================
            
            /// <summary>
            /// ?? USER CLAIMS TABLE
            /// Stores custom claims/permissions for individual users
            /// 
            /// ?? Primary Key: Id
            /// ?? Foreign Key: UserId ? AspNetUsers.Id
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            // ====================================================================
            // ?? TABLE 5: AspNetUserLogins
            // ====================================================================
            
            /// <summary>
            /// ?? USER LOGINS TABLE
            /// Stores external login providers (Google, Facebook, etc.)
            /// 
            /// ?? Composite Primary Key: (LoginProvider, ProviderKey)
            /// ?? Foreign Key: UserId ? AspNetUsers.Id
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            // ====================================================================
            // ?? TABLE 6: AspNetUserRoles (Junction Table)
            // ====================================================================
            
            /// <summary>
            /// ?? USER ROLES JUNCTION TABLE
            /// Links users to roles (many-to-many relationship)
            /// 
            /// ?? Composite Primary Key: (UserId, RoleId)
            /// ?? Foreign Keys: UserId ? AspNetUsers.Id, RoleId ? AspNetRoles.Id
            /// 
            /// ?? ASSIGNMENT 2.4 - Role-based authorization:
            /// This table enables users to have multiple roles
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            // ====================================================================
            // ?? TABLE 7: AspNetUserTokens
            // ====================================================================
            
            /// <summary>
            /// ?? USER TOKENS TABLE
            /// Stores authentication tokens (password reset, etc.)
            /// 
            /// ?? Composite Primary Key: (UserId, LoginProvider, Name)
            /// ?? Foreign Key: UserId ? AspNetUsers.Id
            /// </summary>
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            // ====================================================================
            // ?? RELATIONSHIP CONFIGURATIONS
            // ====================================================================
            
            /// <summary>
            /// ?? FOREIGN KEY CONSTRAINTS
            /// These define how tables relate and what happens on delete.
            /// 
            /// ?? ASSIGNMENT 3.4 - Data Integrity:
            /// Cascade delete means: if parent is deleted, children are deleted.
            /// This prevents orphaned records!
            /// </summary>
            
            // RoleClaims ? Roles (many-to-one)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)  // Delete claims if role deleted
                        .IsRequired();
                });

            // UserClaims ? Users (many-to-one)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            // UserLogins ? Users (many-to-one)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            // UserRoles ? Users and Roles (junction)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            // UserTokens ? Users (many-to-one)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

/// <summary>
/// ?? EDUCATIONAL SUMMARY - MODEL SNAPSHOT PURPOSE:
/// 
/// ?? WHAT EF CORE DOES WITH THIS FILE:
/// 
/// 1?? When you add a migration:
///    - Reads this snapshot (current database state)
///    - Scans your entity classes (desired state)
///    - Generates migration with differences
/// 
/// 2?? When you update database:
///    - Uses this to know what tables/columns to create
/// 
/// 3?? When you scaffold:
///    - Can reverse-engineer database into C# classes
/// 
/// ?? COMMON MISTAKES TO AVOID:
/// ? Editing this file manually
/// ? Change entity classes and add new migration
/// 
/// ? Deleting this file
/// ? Keep it in source control!
/// 
/// ? Ignoring when merging branches
/// ? Resolve migration conflicts carefully
/// 
/// ?? WHAT'S MISSING (for future migrations):
/// - Bookings table
/// - ConferenceRooms table
/// - Sessions table
/// - Soft delete fields (IsActive)
/// - CreatedAt/CancelledAt timestamps
/// </summary>