// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    /// <summary>
    /// ?? ASSIGNMENT 3.1, 3.2, 3.4 - Complete Database Model Snapshot
    /// 
    /// ?? WHAT THIS FILE REPRESENTS:
    /// This is the COMPLETE picture of your database schema including:
    /// ? Identity tables (AspNetUsers, AspNetRoles, etc.)
    /// ? Domain entities (Bookings, ConferenceRooms)
    /// ? All relationships, keys, and constraints
    /// 
    /// ?? THIS IS THE SOURCE OF TRUTH:
    /// EF Core uses this file to know what your database looks like.
    /// When you add new migrations, it compares this snapshot to your
    /// current entity classes to detect changes.
    /// 
    /// ?? CRITICAL RULE: NEVER EDIT THIS FILE MANUALLY!
    /// This is automatically generated and updated by EF Core.
    /// To change your schema:
    /// 1. Modify your entity classes
    /// 2. Run: dotnet ef migrations add YourChange
    /// 3. EF Core updates this file automatically
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210183818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // ?? EF Core version that created this snapshot
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // ====================================================================
            // ?? SECTION 1: IDENTITY TABLES (AUTHENTICATION)
            // ====================================================================
            
            /// <summary>
            /// ?? IDENTITY TABLES - Provided by ASP.NET Core Identity
            /// These tables handle all authentication and authorization:
            /// - Users, Roles, Claims, Logins, Tokens
            /// 
            /// ?? ASSIGNMENT 2.4 - Authentication/Authorization
            /// </summary>

            // ?? USERS TABLE
            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            // ?? ROLES TABLE
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            // ?? ROLE CLAIMS TABLE
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // ?? USER CLAIMS TABLE
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            // ?? EXTERNAL LOGINS TABLE (Google, Facebook, etc.)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            // ?? USER-ROLES JUNCTION TABLE (many-to-many)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            // ??? USER TOKENS TABLE (password reset, etc.)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            // ====================================================================
            // ?? SECTION 2: DOMAIN ENTITIES (CONFERENCE BOOKING SYSTEM)
            // ====================================================================
            
            /// <summary>
            /// ?? DOMAIN ENTITIES - Your business data
            /// These tables store the actual conference booking information:
            /// - ConferenceRooms: Available rooms
            /// - Bookings: Reservations made by users
            /// 
            /// ?? ASSIGNMENT 3.1 - Persistence
            /// ?? ASSIGNMENT 3.2 - Schema Evolution
            /// ?? ASSIGNMENT 3.4 - Data Integrity
            /// </summary>

            // ?? CONFERENCE ROOMS TABLE
            modelBuilder.Entity("BookingSystem.ConferenceRoom", b =>
                {
                    // ?? Primary Key
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()  // Auto-increment
                        .HasColumnType("INTEGER");

                    // ?? Room capacity (max people)
                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    // ?? ?? ASSIGNMENT 3.4 - Soft delete flag
                    // true = active (available), false = inactive (soft-deleted)
                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    // ?? Room identifier (e.g., "A101", "B202")
                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // ?? ?? ASSIGNMENT 3.2 - Physical location
                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // ?? Room type stored as INTEGER (enum value)
                    // 0 = Standard, 1 = Training, 2 = Conference, 3 = Boardroom
                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("conRooms");
                });

            // ?? BOOKINGS TABLE
            modelBuilder.Entity("BookingSystem.Booking", b =>
                {
                    // ?? Primary Key
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // ?? ?? ASSIGNMENT 3.2 - When booking was created
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    
                    // ?? MISSING: CancelledAt (should be added in next migration)

                    // ?? When the booking ends
                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    // ?? Foreign Key to ConferenceRoom
                    b.Property<int>("RoomID")
                        .HasColumnType("INTEGER");

                    // ?? When the booking starts
                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    // ?? Booking status stored as INTEGER (enum value)
                    // 0 = Pending, 1 = Confirmed, 2 = Cancelled, 3 = Completed
                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    // ?? Index for faster queries by RoomID
                    b.HasIndex("RoomID");

                    b.ToTable("bookings");
                });

            // ====================================================================
            // ?? SECTION 3: RELATIONSHIPS & FOREIGN KEYS
            // ====================================================================
            
            /// <summary>
            /// ?? RELATIONSHIP CONFIGURATIONS
            /// These define how tables relate to each other:
            /// - Bookings ? Rooms (many-to-one)
            /// - All Identity relationships
            /// 
            /// ?? ASSIGNMENT 3.4 - Referential Integrity
            /// </summary>

            // ?? BOOKINGS ? ROOMS relationship
            modelBuilder.Entity("BookingSystem.Booking", b =>
                {
                    b.HasOne("BookingSystem.ConferenceRoom", "Room")
                        .WithMany()  // Room can have many bookings
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)  // If room deleted, delete its bookings
                        .IsRequired();

                    b.Navigation("Room");
                });

            // ?? All Identity relationships (auto-configured by EF)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

/// <summary>
/// ?? EDUCATIONAL SUMMARY - COMPLETE DATABASE SCHEMA:
/// 
/// ?? TABLES IN YOUR DATABASE (11 tables total):
/// 
/// 1?? IDENTITY TABLES (7 tables):
///    - AspNetUsers         ?? User accounts
///    - AspNetRoles         ?? Role definitions
///    - AspNetUserRoles     ?? User-role assignments
///    - AspNetRoleClaims    ?? Role permissions
///    - AspNetUserClaims    ?? User-specific claims
///    - AspNetUserLogins    ?? External logins
///    - AspNetUserTokens    ??? Auth tokens
/// 
/// 2?? DOMAIN TABLES (2 tables):
///    - conRooms            ?? Conference rooms
///    - bookings            ?? Room bookings
/// 
/// ?? ASSIGNMENT CHECKLIST:
/// 
/// ? 2.4 - Authentication/Authorization:
///    - All Identity tables present
///    - Ready for JWT tokens
/// 
/// ? 3.1 - Persistence:
///    - Domain tables created
///    - Data can be saved/retrieved
/// 
/// ? 3.2 - Schema Evolution:
///    - Room: location, IsActive
///    - Booking: Status, CreatedAt
///    ? MISSING: Booking.CancelledAt
/// 
/// ? 3.3 - Performance:
///    - Index on bookings.RoomID
/// 
/// ? 3.4 - Data Integrity:
///    - Foreign key (RoomID ? conRooms.ID)
///    - Cascade delete configured
///    - Soft delete via IsActive
/// 
/// ?? NEXT STEPS:
/// 1. Add missing CancelledAt column to Bookings
/// 2. Add Sessions table if required
/// 3. Consider adding more indexes for common queries
/// </summary>