// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    /// <summary>
    /// ?? ASSIGNMENT 3.1, 3.2, 3.3, 3.4 - COMPLETE DATABASE MODEL SNAPSHOT
    /// 
    /// ?? WHAT IS THIS FILE?
    /// This is the OFFICIAL BLUEPRINT of your entire database.
    /// Think of it like the architectural plans for a building:
    /// - Shows every room (table)
    /// - Shows every door (relationship)
    /// - Shows every window (column)
    /// 
    /// ?? WHY IS THIS CRITICAL?
    /// 1. **Source of Truth**: EF Core compares this to your C# classes to detect changes
    /// 2. **Migration Generation**: When you add a migration, EF Core reads this file
    /// 3. **Team Coordination**: Everyone on the team has the same schema reference
    /// 4. **Deployment**: Ensures database is created correctly in production
    /// 
    /// ?? THE GOLDEN RULE: NEVER EDIT THIS FILE MANUALLY!
    /// This is 100% machine-generated. To change your database:
    /// 1. Change your entity classes (Booking.cs, ConferenceRoom.cs)
    /// 2. Run: dotnet ef migrations add YourChangeName
    /// 3. EF Core updates this file automatically
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // ?? EF Core version that created this snapshot
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // ====================================================================
            // ?? SECTION 1: IDENTITY TABLES (ASSIGNMENT 2.4)
            // ====================================================================
            
            /// <summary>
            /// ?? IDENTITY TABLES - Authentication & Authorization
            /// These 7 tables are the ENGINE of your security system.
            /// They handle: user accounts, passwords, roles, permissions.
            /// 
            /// ?? ASSIGNMENT 2.4 REQUIREMENTS:
            /// ? User accounts (AspNetUsers)
            /// ? Roles (AspNetRoles) 
            /// ? User-Role assignments (AspNetUserRoles)
            /// ? Ready for JWT authentication
            /// </summary>

            // ?? TABLE 1: AspNetUsers - User Accounts
            // Stores all user information: usernames, emails, password hashes
            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");  // Failed login attempts

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");  // Prevents concurrent updates

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");  // Email verified?

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");  // Can user be locked out?

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");  // When lockout expires

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");  // Uppercase email for fast lookup

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");  // Uppercase username for fast lookup

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");  // NEVER plain text! Hashed password

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");  // Changes when password changes

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");  // 2FA enabled?

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");  // Primary Key

                    // ?? Indexes for fast lookups
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            // ?? TABLE 2: AspNetRoles - Role Definitions
            // Stores all roles: "Admin", "Employee", "Receptionist", "Facilities Manager"
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            // ?? TABLE 3: AspNetRoleClaims - Role Permissions
            // Stores permissions assigned to roles (e.g., "CanDeleteRooms" for Admin)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // ?? TABLE 4: AspNetUserClaims - User-Specific Claims
            // Stores custom data for individual users
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            // ?? TABLE 5: AspNetUserLogins - External Logins
            // Stores external login info (Google, Facebook, Microsoft accounts)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            // ?? TABLE 6: AspNetUserRoles - User-Role Junction
            // Links users to roles (many-to-many relationship)
            // One user can have many roles, one role can have many users
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");  // Composite primary key

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            // ??? TABLE 7: AspNetUserTokens - Authentication Tokens
            // Stores password reset tokens, email confirmation tokens, etc.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");  // Composite key

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            // ====================================================================
            // ?? SECTION 2: DOMAIN ENTITIES (ASSIGNMENT 3.1, 3.2, 3.3, 3.4)
            // ====================================================================
            
            /// <summary>
            /// ?? DOMAIN ENTITIES - Your Business Data
            /// These tables store the actual conference booking information.
            /// 
            /// ?? ASSIGNMENT 3.1 - Persistence
            /// ? Data now saved to database, not memory
            /// 
            /// ?? ASSIGNMENT 3.2 - Schema Evolution
            /// ? Room: location, IsActive
            /// ? Booking: Status, CreatedAt
            /// ? MISSING: Booking.CancelledAt (add in next migration!)
            /// 
            /// ?? ASSIGNMENT 3.3 - Performance
            /// ? Index on bookings.RoomID for faster queries
            /// 
            /// ?? ASSIGNMENT 3.4 - Data Integrity
            /// ? Foreign key relationship
            /// ? Cascade delete
            /// ? Soft delete via IsActive
            /// ? MISSING: UserId in Bookings (track who booked)
            /// </summary>

            // ?? TABLE 8: conRooms - Conference Rooms
            // Stores all room information
            modelBuilder.Entity("BookingSystem.ConferenceRoom", b =>
                {
                    // ?? Primary Key - Auto-incrementing integer
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // ?? Room capacity (max people)
                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    // ?? ?? ASSIGNMENT 3.4 - Soft delete flag
                    // true = active (available for booking)
                    // false = inactive (soft-deleted, under maintenance)
                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    // ?? Room identifier (e.g., "A101", "B202", "Conference Hall")
                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // ?? ?? ASSIGNMENT 3.2 - Physical location
                    // e.g., "Floor 1, Building A", "Cape Town Office"
                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // ?? Room type stored as INTEGER (enum value)
                    // 0 = Standard, 1 = Training, 2 = Conference, 3 = Boardroom
                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("conRooms");
                });

            // ?? TABLE 9: bookings - Room Bookings
            // Stores all reservation records
            modelBuilder.Entity("BookingSystem.Booking", b =>
                {
                    // ?? Primary Key - Auto-incrementing integer
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // ?? ?? ASSIGNMENT 3.2 - When booking was created
                    // Used for audit trails and reporting
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    // ?? When the booking ends
                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    // ?? Foreign Key to ConferenceRoom
                    b.Property<int>("RoomID")
                        .HasColumnType("INTEGER");

                    // ?? When the booking starts
                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    // ?? Booking status stored as INTEGER (enum value)
                    // 0 = Pending, 1 = Confirmed, 2 = Cancelled, 3 = Completed
                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    // ?? ?? ASSIGNMENT 3.3 - Index for performance
                    // Makes queries like "find all bookings for room 5" FAST
                    b.HasIndex("RoomID");

                    b.ToTable("bookings");
                });

            // ====================================================================
            // ?? SECTION 3: RELATIONSHIPS & FOREIGN KEYS (ASSIGNMENT 3.4)
            // ====================================================================
            
            /// <summary>
            /// ?? RELATIONSHIP CONFIGURATIONS
            /// These define how tables connect to each other.
            /// 
            /// ?? ASSIGNMENT 3.4 - Referential Integrity
            /// - Prevents orphaned records
            /// - Ensures data consistency
            /// - Defines delete behavior
            /// </summary>

            // ?? BOOKINGS ? ROOMS relationship (Many-to-One)
            // One room can have many bookings
            // One booking belongs to one room
            modelBuilder.Entity("BookingSystem.Booking", b =>
                {
                    b.HasOne("BookingSystem.ConferenceRoom", "Room")
                        .WithMany()  // Room doesn't have a Bookings collection (could add later)
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)  // If room deleted, delete its bookings
                        .IsRequired();

                    b.Navigation("Room");  // Enables b.Room navigation property
                });

            // ?? All Identity relationships (auto-configured by EF)
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

/// <summary>
/// ?? COMPLETE DATABASE SUMMARY - 9 TABLES TOTAL:
/// 
/// ?? IDENTITY TABLES (7) - Authentication & Authorization:
/// +---------------------------------------------------------------+
/// ¦ Table           ¦ Purpose                                     ¦
/// +-----------------+---------------------------------------------¦
/// ¦ AspNetUsers     ¦ User accounts with passwords                ¦
/// ¦ AspNetRoles     ¦ Role definitions (Admin, Employee, etc.)    ¦
/// ¦ AspNetUserRoles ¦ Links users to roles (many-to-many)         ¦
/// ¦ AspNetRoleClaims¦ Permissions assigned to roles               ¦
/// ¦ AspNetUserClaims¦ Custom data for individual users            ¦
/// ¦ AspNetUserLogins¦ External login providers (Google, etc.)     ¦
/// ¦ AspNetUserTokens¦ Password reset, email confirmation tokens   ¦
/// +---------------------------------------------------------------+
/// 
/// ?? DOMAIN TABLES (2) - Conference Booking:
/// +----------------------------------------------------------+
/// ¦ Table      ¦ Columns                                      ¦
/// +------------+---------------------------------------------¦
/// ¦ conRooms   ¦ ID, RoomNumber, Capacity, type, location,   ¦
/// ¦            ¦ IsActive ? (soft delete)                    ¦
/// +------------+---------------------------------------------¦
/// ¦ bookings   ¦ Id, RoomID (FK), StartTime, EndTime,        ¦
/// ¦            ¦ Status ?, CreatedAt ?                      ¦
/// ¦            ¦ ? Missing: CancelledAt, UserId              ¦
/// +----------------------------------------------------------+
/// 
/// ?? ASSIGNMENT COMPLETION CHECKLIST:
/// 
/// ? 2.4 - Authentication/Authorization:
///    - All 7 Identity tables present
///    - Ready for JWT tokens
/// 
/// ? 3.1 - Persistence:
///    - Domain tables created
///    - Data can be saved/retrieved
/// 
/// ? 3.2 - Schema Evolution:
///    - Room: location, IsActive
///    - Booking: Status, CreatedAt
///    ? NEEDS: Booking.CancelledAt
/// 
/// ? 3.3 - Performance:
///    - Index on bookings.RoomID
///    ? Could add more indexes (StartTime, Status)
/// 
/// ? 3.4 - Data Integrity:
///    - Foreign key (RoomID ? conRooms.ID)
///    - Cascade delete configured
///    - Soft delete via IsActive
///    ? NEEDS: UserId to track who booked
/// 
/// ?? NEXT MIGRATIONS NEEDED:
/// 1. Add CancelledAt to Bookings (Assignment 3.2)
/// 2. Add UserId to Bookings (Assignment 2.4/3.4)
/// 3. Create Sessions table (if required)
/// 4. Add more indexes for common queries (Assignment 3.3)
/// 
/// ?? COMMANDS TO ADD MISSING COLUMNS:
/// 
/// // Add CancelledAt
/// dotnet ef migrations add AddCancelledAtToBookings
/// 
/// // Add UserId and relationship
/// dotnet ef migrations add AddUserIdToBookings
/// </summary>