#nullable disable

namespace BookingSystem
{
    /// <summary>
    /// 📌 ASSIGNMENT 3.1, 3.2, 3.4 - Conference Room Domain Entity
    /// 
    /// 🎓 WHAT IS THIS?
    /// This represents a physical conference room in your system.
    /// It's a DOMAIN ENTITY - has both data AND behavior.
    /// 
    /// 🎓 DOMAIN ENTITY CHARACTERISTICS:
    /// - Has an identity (ID) that stays the same even if properties change
    /// - Contains business logic/rules
    /// - Is responsible for its own data integrity
    /// - Used by services/repositories to persist data
    /// </summary>
    public class ConferenceRoom
    {
        // ====================================================================
        // 📌 PROPERTIES - What a Room IS
        // ====================================================================

        /// <summary>
        /// 🎓 Primary Key - Unique identifier for this room
        /// 
        /// ⚠️ NOTE: Capital "ID" (not "Id" like in Booking)
        /// Consistency issue: Booking uses "Id", Room uses "ID"
        /// Best practice: Pick one convention and stick with it!
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// 🎓 Room identifier for users (e.g., "A101", "Conference Hall A")
        /// This is what users see and refer to
        /// Should be unique in the system
        /// </summary>
        public string RoomNumber { get; set; }

        /// <summary>
        /// 🎓 Maximum number of people the room can hold
        /// Used for:
        /// - Filtering rooms by size (Assignment 3.3)
        /// - Validating bookings (can't book 30 people in a 15-capacity room)
        /// </summary>
        public int Capacity { get; set; }

        /// <summary>
        /// 🎓 Type of room (enum)
        /// Values: Standard, Training, Conference, Boardroom
        /// Stored as INTEGER in database
        /// </summary>
        public RoomType type { get; set; }

        /// <summary>
        /// 🎓 📌 ASSIGNMENT 3.2 - Physical location of the room
        /// Example: "Floor 1, Building A", "Cape Town Office", "North Wing"
        /// 
        /// ⚠️ NOTE: lowercase 'l' - consistency issue with other properties
        /// C# convention: PascalCase for properties (Location)
        /// </summary>
        public string location { get; set; }

        /// <summary>
        /// 🎓 📌 ASSIGNMENT 3.4 - Soft delete flag
        /// true = room is ACTIVE (available for booking)
        /// false = room is INACTIVE (soft-deleted, under maintenance)
        /// 
        /// Instead of deleting rooms, we just flip this flag
        /// Preserves historical data and prevents orphaned bookings
        /// </summary>
        public bool IsActive { get; set; }

        // ====================================================================
        // 📌 CONSTRUCTORS - How a Room is CREATED
        // ====================================================================

        /// <summary>
        /// 🎓 Parameterless constructor (required by EF Core)
        /// EF Core needs this to create objects when reading from database
        /// </summary>
        public ConferenceRoom() { }

        /// <summary>
        /// 📌 Business constructor - Creates a new conference room
        /// 
        /// 🎓 WHAT THIS CONSTRUCTOR DOES:
        /// 1. Validates input (room number, capacity)
        /// 2. Sets default values (location = "Not found", IsActive = true)
        /// 3. Creates a new room entity
        /// 
        /// 📌 ISSUES TO FIX:
        /// 1. ❌ Using Exception (too generic) - use specific exceptions
        /// 2. ❌ Hardcoded capacity range (10-20) - maybe too restrictive?
        /// 3. ❌ Setting ID manually - should be auto-generated by DB
        /// 4. ❌ location default "Not found" - better to require or use null
        /// 5. ❌ No validation for RoomNumber format
        /// 
        /// 🎓 BETTER VERSION:
        /// public ConferenceRoom(string roomNumber, int capacity, RoomType type, string location)
        /// {
        ///     if (string.IsNullOrWhiteSpace(roomNumber))
        ///         throw new ArgumentException("Room number is required", nameof(roomNumber));
        ///     
        ///     if (capacity <= 0)
        ///         throw new ArgumentException("Capacity must be positive", nameof(capacity));
        ///     
        ///     if (string.IsNullOrWhiteSpace(location))
        ///         throw new ArgumentException("Location is required", nameof(location));
        ///     
        ///     RoomNumber = roomNumber;
        ///     Capacity = capacity;
        ///     this.type = type;
        ///     Location = location;
        ///     IsActive = true;
        ///     // ID is NOT set - database will generate
        /// }
        /// </summary>
        public ConferenceRoom(int id, string roomNumber, int capacity, RoomType type)
        {
            // 🎓 Validation
            if (string.IsNullOrWhiteSpace(roomNumber))
            {
                throw new Exception("A room number must be entered");
                // ❌ Exception too generic - use ArgumentException
            }
            
            // 🎓 Business rule: Capacity must be between 10 and 20
            // ⚠️ This might be too restrictive for real conference rooms!
            // Some rooms could be smaller (meeting rooms) or larger (ballrooms)
            if (capacity < 10 || capacity > 20)
            {
                throw new Exception("Capacity must be between 10 and 20");
                //Assuming there are rooms with a min of 10 and the max of 20
            }

            // ⚠️ Setting ID manually - database should generate this!
            // If client sends ID, we should ignore it
            ID = id;
            
            RoomNumber = roomNumber;
            Capacity = capacity;
            this.type = type;
            
            // 🎓 Default values for new rooms
            location = "Not found";  // ❌ Better to require location
            IsActive = true;          // ✅ New rooms are active by default
        }

        // ====================================================================
        // 📌 MISSING BEHAVIORS - What a Room CAN DO
        // ====================================================================

        /// <summary>
        /// 🎓 METHODS THAT SHOULD BE ADDED:
        /// 
        /// // Soft delete - deactivate room
        /// public void Deactivate()
        /// {
        ///     IsActive = false;
        /// }
        /// 
        /// // Reactivate room
        /// public void Activate()
        /// {
        ///     IsActive = true;
        /// }
        /// 
        /// // Update location
        /// public void UpdateLocation(string newLocation)
        /// {
        ///     if (string.IsNullOrWhiteSpace(newLocation))
        ///         throw new ArgumentException("Location cannot be empty");
        ///     location = newLocation;
        /// }
        /// 
        /// // Update capacity (with validation)
        /// public void UpdateCapacity(int newCapacity)
        /// {
        ///     if (newCapacity <= 0)
        ///         throw new ArgumentException("Capacity must be positive");
        ///     Capacity = newCapacity;
        /// }
        /// </summary>
    }
}

/// <summary>
/// 🎓 EDUCATIONAL SUMMARY - CONFERENCE ROOM ENTITY:
/// 
/// 📌 WHAT'S GOOD:
/// ✅ Has all required properties for assignments
/// ✅ IsActive for soft delete (Assignment 3.4)
/// ✅ location field (Assignment 3.2)
/// ✅ Basic validation in constructor
/// 
/// 📌 WHAT NEEDS IMPROVEMENT:
/// 
/// 1️⃣ NAMING CONSISTENCY:
///    - Property: ID vs Id (Booking uses Id)
///    - Property: type vs Type (PascalCase convention)
///    - Property: location vs Location (PascalCase convention)
/// 
/// 2️⃣ CONSTRUCTOR ISSUES:
///    - Takes ID parameter (should be DB-generated)
///    - Capacity range 10-20 (too restrictive)
///    - Uses Exception instead of specific exceptions
///    - location default "Not found" (better to require)
/// 
/// 3️⃣ MISSING BEHAVIORS:
///    - No Deactivate() method (soft delete)
///    - No Activate() method
///    - No UpdateLocation() method
///    - No UpdateCapacity() method
/// 
/// 4️⃣ BUSINESS RULES (Assignment 3.4):
///    - Should prevent booking if IsActive = false
///    - Should ensure RoomNumber is unique
///    - Should validate location format
/// 
/// 🚀 IMPROVED VERSION:
/// 
/// public class ConferenceRoom
/// {
///     public int Id { get; set; }  // Consistent with Booking
///     public string RoomNumber { get; set; }
///     public int Capacity { get; set; }
///     public RoomType Type { get; set; }  // PascalCase
///     public string Location { get; set; }  // PascalCase
///     public bool IsActive { get; set; }
/// 
///     private ConferenceRoom() { } // For EF Core
/// 
///     public ConferenceRoom(string roomNumber, int capacity, RoomType type, string location)
///     {
///         SetRoomNumber(roomNumber);
///         SetCapacity(capacity);
///         Type = type;
///         SetLocation(location);
///         IsActive = true;
///     }
/// 
///     public void SetRoomNumber(string roomNumber)
///     {
///         if (string.IsNullOrWhiteSpace(roomNumber))
///             throw new ArgumentException("Room number required");
///         RoomNumber = roomNumber;
///     }
/// 
///     public void SetCapacity(int capacity)
///     {
///         if (capacity <= 0)
///             throw new ArgumentException("Capacity must be positive");
///         // Remove the 10-20 restriction or make it configurable
///         Capacity = capacity;
///     }
/// 
///     public void SetLocation(string location)
///     {
///         if (string.IsNullOrWhiteSpace(location))
///             throw new ArgumentException("Location required");
///         Location = location;
///     }
/// 
///     public void Deactivate() => IsActive = false;
///     public void Activate() => IsActive = true;
/// }
/// </summary>