using System.Text.Json.Serialization;

namespace ConferenceRoomBooking.Domain.DTOs;

/// <summary>
/// RFC 7807 compliant problem details response
/// Used for ALL error responses (400, 404, 422, 500, etc.)
/// </summary>
public class ProblemDetailsResponse
{
    /// <summary>
    /// A URI reference that identifies the problem type
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server
    /// </summary>
    [JsonPropertyName("status")]
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence
    /// </summary>
    [JsonPropertyName("detail")]
    public string Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence
    /// </summary>
    [JsonPropertyName("instance")]
    public string Instance { get; set; }

    /// <summary>
    /// Application-specific error code
    /// </summary>
    [JsonPropertyName("errorCode")]
    public string ErrorCode { get; set; }

    /// <summary>
    /// Optional trace identifier for support requests
    /// </summary>
    [JsonPropertyName("traceId")]
    public string TraceId { get; set; }

    /// <summary>
    /// Dictionary of field-specific errors (for validation errors)
    /// </summary>
    [JsonPropertyName("errors")]
    public Dictionary<string, string[]> Errors { get; set; } = new();

    /// <summary>
    /// Suggested actions for the client
    /// </summary>
    [JsonPropertyName("suggestions")]
    public List<string> Suggestions { get; set; } = new();

    // Factory methods for common error scenarios
    public static ProblemDetailsResponse ValidationError(
        string detail, 
        Dictionary<string, string[]> errors = null,
        string instance = null,
        string traceId = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.1",
            Title = "One or more validation errors occurred",
            Status = 400,
            Detail = detail,
            Instance = instance,
            TraceId = traceId,
            Errors = errors ?? new Dictionary<string, string[]>(),
            Suggestions = new List<string> { "Check the 'errors' property for details" }
        };
    }

    public static ProblemDetailsResponse BusinessRuleViolation(
        string errorCode,
        string detail,
        List<string> suggestions = null,
        string instance = null,
        string traceId = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.21",
            Title = "Business rule violation",
            Status = 422,
            Detail = detail,
            Instance = instance,
            ErrorCode = errorCode,
            TraceId = traceId,
            Suggestions = suggestions ?? new List<string> { "Review your request against business rules" }
        };
    }

    public static ProblemDetailsResponse NotFound(
        string resourceType,
        string resourceId,
        string instance = null,
        string traceId = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.4",
            Title = "Resource not found",
            Status = 404,
            Detail = $"{resourceType} with ID '{resourceId}' was not found",
            Instance = instance,
            TraceId = traceId,
            Suggestions = new List<string> { "Verify the resource ID", "Check if the resource was deleted" }
        };
    }

    public static ProblemDetailsResponse InternalServerError(
        string traceId,
        string instance = null,
        bool includeDetail = false,
        string detail = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.6.1",
            Title = "Internal server error",
            Status = 500,
            Detail = includeDetail ? detail : "An unexpected error occurred",
            Instance = instance,
            TraceId = traceId,
            Suggestions = new List<string> { "Try again later", "Contact support with the traceId" }
        };
    }

    public static ProblemDetailsResponse Conflict(
        string detail,
        string errorCode = null,
        string instance = null,
        string traceId = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.8",
            Title = "Conflict",
            Status = 409,
            Detail = detail,
            Instance = instance,
            ErrorCode = errorCode,
            TraceId = traceId,
            Suggestions = new List<string> { "Check the current state of the resource", "Retry with updated data" }
        };
    }
}