using BookingSystem;

#nullable disable

namespace BookingSystem.Domain.Entities
{
    /// <summary>
    /// 📌 ASSIGNMENT 2.4, 3.1, 3.2, 3.4 - Booking Domain Entity
    /// 
    /// 🎓 WHAT IS A DOMAIN ENTITY?
    /// A domain entity represents a core business concept in your system.
    /// It contains:
    /// - **Data** (properties) - What the entity IS
    /// - **Behavior** (methods) - What the entity CAN DO
    /// 
    /// 🎓 DOMAIN ENTITY VS DTO:
    /// ┌─────────────────┬─────────────────────────────┐
    /// │ Entity (Booking)│ DTO (BookingListItemDto)    │
    /// ├─────────────────┼─────────────────────────────┤
    /// │ Has behavior    │ Just data                    │
    /// │ Business rules  │ No logic                     │
    
    /// │ Knows about DB  │ Knows nothing about DB       │
    /// └─────────────────┴─────────────────────────────┘
    /// </summary>
    public class Booking
    {
        // ====================================================================
        // 📌 PROPERTIES - What a Booking IS
        // ====================================================================

        /// <summary>
        /// 🎓 Foreign Key to ConferenceRoom
        /// This establishes the database relationship
        /// 📌 ASSIGNMENT 3.4 - Data Integrity: Foreign key ensures room exists
        /// </summary>
        public int RoomId { get; set; }  

        /// <summary>
        /// 🎓 Navigation Property to ConferenceRoom
        /// Allows us to access room details: booking.Room.RoomNumber
        /// EF Core automatically populates this when you use .Include(b => b.Room)
        /// </summary>
        public ConferenceRoom Room { get; set; }  

        /// <summary>
        /// 🎓 Primary Key - Unique identifier for this booking
        /// Auto-generated by database (identity/auto-increment)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 🎓 When the booking starts
        /// Used for:
        /// - Checking conflicts (double-booking prevention)
        /// - Displaying in calendars
        /// - Sorting/filtering (Assignment 3.3)
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 🎓 When the booking ends
        /// Must be after StartTime (enforced in domain logic)
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 🎓 Current status of the booking (enum)
        /// 📌 ASSIGNMENT 3.2 - Status field added
        /// Values:
        /// - Pending    = 0 (Awaiting confirmation)
        /// - Confirmed  = 1 (Approved)
        /// - Cancelled  = 2 (Cancelled by user)
        /// - Completed  = 3 (Meeting has taken place)
        /// </summary>
        public BookingStatus Status { get; set; }

        /// <summary>
        /// 🎓 📌 ASSIGNMENT 3.2 - Timestamp when booking was created
        /// Used for:
        /// - Audit trails
        /// - Sorting (newest first)
        /// - Reporting
        /// 
        /// Default value = DateTime.UtcNow (set when object created)
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// 🎓 📌 ASSIGNMENT 3.2 - Timestamp when booking was cancelled (nullable)
        /// Null = booking not cancelled
        /// Has value = booking was cancelled at this time
        /// 
        /// Used for:
        /// - Reporting cancellation rates
        /// - Audit trails
        /// - Calculating time between booking and cancellation
        /// </summary>
        public DateTime? CancelledAt { get; set; }

        // ====================================================================
        // 📌 CONSTRUCTORS - How a Booking is CREATED
        // ====================================================================

        /// <summary>
        /// 🎓 Parameterless constructor (required by EF Core)
        /// EF Core needs this to create objects when reading from database
        /// </summary>
        public Booking() { }

        /// <summary>
        /// 🎓 Business constructor - Creates a new booking
        /// 
        /// 📌 ISSUES TO FIX:
        /// 1. ❌ No validation (should check room not null, start < end)
        /// 2. ❌ Doesn't set RoomId (foreign key)
        /// 3. ❌ Status should default to Pending (currently defaults to 0 anyway)
        /// 
        /// 🎓 BETTER VERSION:
        /// public Booking(ConferenceRoom room, DateTime start, DateTime end)
        /// {
        ///     Room = room ?? throw new ArgumentNullException(nameof(room));
        ///     RoomId = room.ID;  // Set foreign key
        ///     
        ///     if (start >= end)
        ///         throw new ArgumentException("Start time must be before end time");
        ///     
        ///     if (start < DateTime.UtcNow)
        ///         throw new ArgumentException("Cannot book in the past");
        ///         
        ///     StartTime = start;
        ///     EndTime = end;
        ///     Status = BookingStatus.Pending;  // Explicit default
        ///     CreatedAt = DateTime.UtcNow;
        /// }
        /// </summary>
        public Booking(ConferenceRoom room, DateTime start, DateTime end)
        {
            Room = room;
            StartTime = start;
            EndTime = end;
            // ⚠️ RoomId not set! EF might not save relationship correctly
            // ⚠️ No validation!
            // ⚠️ Status defaults to 0 (Pending) automatically
        }

        // ====================================================================
        // 📌 BEHAVIORS - What a Booking CAN DO
        // ====================================================================

        /// <summary>
        /// 📌 Confirm the booking
        /// Changes status from Pending to Confirmed
        /// 
        /// 🎓 BUSINESS RULES:
        /// - Can only confirm Pending bookings
        /// - Should check if room is still available? (maybe in service layer)
        /// 
        /// 🎓 USAGE:
        /// var booking = new Booking(room, start, end);
        /// booking.Confirm();  // Now Status = Confirmed
        /// </summary>
        public void Confirm()
        {
            // ⚠️ Should check current status!
            // if (Status != BookingStatus.Pending)
            //     throw new InvalidOperationException($"Cannot confirm a {Status} booking");
            
            Status = BookingStatus.Confirmed;
        }

        /// <summary>
        /// 📌 Cancel the booking
        /// Changes status to Cancelled and sets CancelledAt timestamp
        /// 
        /// 🎓 BUSINESS RULES:
        /// - Can cancel Pending or Confirmed bookings
        /// - Cannot cancel Completed bookings
        /// - Records when cancellation happened (Assignment 3.2)
        /// 
        /// 🎓 FLUENT INTERFACE:
        /// Returns 'this' so you can chain: booking.Cancel().SaveChanges();
        /// 
        /// 📌 ASSIGNMENT 3.2 - Sets CancelledAt timestamp
        /// </summary>
        public Booking Cancel()
        {
            // ⚠️ Should check if already cancelled or completed!
            // if (Status == BookingStatus.Completed)
            //     throw new InvalidOperationException("Cannot cancel completed booking");
            
            Status = BookingStatus.Cancelled;
            CancelledAt = DateTime.UtcNow;  // ✅ Record cancellation time
            return this;
        }
    }
}

/// <summary>
/// 🎓 EDUCATIONAL SUMMARY - BOOKING ENTITY:
/// 
/// 📌 WHAT'S GOOD:
/// ✅ Has all required properties for assignments
/// ✅ CancelledAt is nullable (good for DB)
/// ✅ Cancel() sets CancelledAt (Assignment 3.2)
/// ✅ Room navigation property (for eager loading)
/// 
/// 📌 WHAT NEEDS IMPROVEMENT:
/// 
/// 1️⃣ VALIDATION MISSING:
///    - Constructor should validate dates
///    - Confirm() should check current status
///    - Cancel() should check if already cancelled
/// 
/// 2️⃣ FOREIGN KEY ISSUE:
///    - RoomId not set in constructor
///    - EF might not save relationship correctly
///    - Fix: Add RoomId = room.ID in constructor
/// 
/// 3️⃣ BUSINESS RULES MISSING (Assignment 3.4):
///    - Can't book inactive room (check in service layer)
///    - Can't double-book (check in service layer)
///    - Can't book past dates
/// 
/// 4️⃣ STATUS LIFECYCLE:
///    Pending → Confirmed → Completed
///       ↘         ↘
///        Cancelled  Cancelled
/// 
/// 🚀 IMPROVED VERSION:
/// 
/// public Booking(ConferenceRoom room, DateTime start, DateTime end)
/// {
///     if (room == null) 
///         throw new ArgumentNullException(nameof(room));
///     if (!room.IsActive)
///         throw new InvalidOperationException("Cannot book inactive room");
///     if (start >= end)
///         throw new ArgumentException("Start must be before end");
///     if (start < DateTime.UtcNow)
///         throw new ArgumentException("Cannot book past dates");
///     
///     Room = room;
///     RoomId = room.ID;
///     StartTime = start;
///     EndTime = end;
///     Status = BookingStatus.Pending;
///     CreatedAt = DateTime.UtcNow;
/// }
/// 
/// public void Confirm()
/// {
///     if (Status != BookingStatus.Pending)
///         throw new InvalidOperationException($"Cannot confirm {Status} booking");
///     Status = BookingStatus.Confirmed;
/// }
/// 
/// public void Cancel()
/// {
///     if (Status == BookingStatus.Completed)
///         throw new InvalidOperationException("Cannot cancel completed booking");
///     Status = BookingStatus.Cancelled;
///     CancelledAt = DateTime.UtcNow;
/// }
/// </summary>